name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    - name: Build with dotnet
      run: cd src && dotnet build --configuration Release
    - name: Unit test
      run: cd src && dotnet test

